leoelicos/just-kidding

.gitignore
package-lock.json
package.json

Packages I installed
- "bcrypt": "^5.0.1",
- "connect-session-sequelize": "^7.1.4",
- "dotenv": "^16.0.1",
- "express": "^4.18.1",
- "express-handlebars": "^6.0.6",
- "express-session": "^1.17.3",
- "mysql2": "^2.3.3",
- "sequelize": "^6.20.1"
- "eslint": "^8.16.0"

Admin 24 package json

---

.eslintrc.json

eslintrc json created

---

.eslintignore

eslintignore create

---

.env
seeds/user-seeds.js

user seeds
ID
username
email
password
uses bcrypt

created user seed

---

.env
.gitignore
config/connection.js
package-lock.json

updated connections file and also added .env to gitignore

Jess 31 conection.js

---

models/Post.js

```
const { Model, DataTypes } = require('sequelize');
const sequelize = require('../config/connection');
class Post extends Model {}
Post.init(
{
id: {
type: DataTypes.INTEGER,
primaryKey: true,
autoIncrement: true
},
text: {
type: DataTypes.STRING,
allowNull: false
},
title: {
type: DataTypes.STRING,
allowNull: false
},
image_url: {
type: DataTypes.STRING
},
price: {
type: DataTypes.FLOAT,
},
date: {
type: DataTypes.DATE,
allowNull: false,
defaultValue: DataTypes.NOW
},
thread_id: {
type: DataTypes.INTEGER,
references: {
model: 'thread',
key: 'id'
}
},
user_id: {
type: DataTypes.INTEGER,
references: {
model: 'user',
key: 'id'
}
}
},
{
sequelize,
timestamps: false,
freezeTableName: true,
underscored: true,
modelName: 'post'
}
);
module.exports = Post;
```

Implement Post Model

---

models/Thread.js

Thread model created

---

seeds/post-seeds.js

```
const { Post } = require('../models');
const postData = [
{
title: 'Buy my baby\'s nappies',
text: 'Half price, brand new, come and get it! 2 packs for only $35.00',
image_url: 'https://www.bigw.com.au/medias/sys_master/images/images/h25/he8/16831808831518.jpg',
price: 35.00,
thread_id: 0,
user_id: 0
},
{
title: 'I ate my baby\'s candy',
text: 'It was 3am. A dark, hot, hungry woman (me) went downstairs to raid the fridge but there was no food except my baby\'s candy. I\'m such a bad person.',
image_url: 'https://sites.imsa.edu/acronym/files/2021/10/candy.jpg',
thread_id: 0,
user_id: 0
},
{
title: 'You\'ll never get this one!',
text: 'Clues: it\'s related to food',
image_url: 'https://www.momtastic.com/assets/uploads/2016/03/angerharmsbabiesemotionally_sized-1280x720.jpg',
thread_id: …
```

Add some seeds for Post

---

models/Thread.js
seeds/thread-seeds.js

thread seed created & checked with lint

thread seed created & checked with lint

---

models/User.js

this should be the user model in the right place

updating user model

---

models/index.js

this is the index file for the model
`const Thread = require('./Thread');
const User = require('./User');
const Post = require('./Post');
Post.belongsTo(Thread, {
foreignKey: 'thread_id',
});
Thread.hasMany(Post, {
foreignKey: 'thread_id',
onDelete: 'CASCADE',
});
Post.belongsTo(User, {
foreignKey: 'user_id',
});
User.hasMany(Post, {
foreignKey: 'user_id',
onDelete: 'CASCADE',
});
module.exports = { Thread, User, Post };
`

making index file for models connection

---

seeds/index.js

```js
const seedThreads = require('./thread-seeds');
const seedUsers = require('./user-seeds');
const seedPosts = require('./post-seeds');
const sequelize = require('../config/connection');
const seedAll = async () => {
await sequelize.sync({ force: true });
//   console.log('\n----- DATABASE SYNCED -----\n');
await seedPosts();
//   console.log('\n----- CATEGORIES SEEDED -----\n');
await seedThreads();
//   console.log('\n----- PRODUCTS SEEDED -----\n');
await seedUsers();
//   console.log('\n----- TAGS SEEDED -----\n');
process.exit(0);
};
seedAll();
```

link thread-seeds, user-seeds, post-seeds

---

seeds/index.js

A bug of seeds not working was fixed by changing the seed order

Change order of seeding - move seedPosts last

---

controllers/homeRoutes.js

homeRoute controller

---

utils/helpers.js

helpers(date) file create

---

controllers/index.js

`const router = require('express').Router();
const apiRoutes = require('./api');
const homeRoutes = require('./homeRoutes');
router.use('/', homeRoutes);
router.use('/api', apiRoutes);
module.exports = router;
`
Connecting the api routes

adding index.js for connecting api routes

---

controllers/api/index.js

```js
const router = require('express').Router();
const postRoutes = require('./postRoutes');
const userRoutes = require('./userRoutes');
router.use('/posts', postRoutes);
router.use('/users', userRoutes);
module.exports = router;
```

Implement postRoutes and userRoutes

---

utils/auth.js

adding util auth

---

controllers/api/userRoutes.js

userRoute create

---

views/login.handlebars

login hadlebars created.
The following link need to be added to the main handlebars:
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
the link to the login.js is missing. I will added and push the changed

login hadlebars created

---

controllers/api/userRoutes.js

logout route added to userRoute file

logout route added to userRoute file

---

views/homepage.handlebars

homepage handlebars Created

---

package-lock.json
package.json

updated pckage json with multer

---

views/login.handlebars

```handlebars
<label for="InputPasswordSignup">Password (min. 8 characters)</label>
<input type="password" class="form-control" id="InputPasswordSignup" placeholder="Password" minlength="8">
```

Add spec. for password, force min length = 8

---

.eslintrc.json
.pretterignore
.prettier.json
config/connection.js
controllers/api/postRoutes.js
controllers/api/userRoutes.js
controllers/homeRoutes.js
models/Post.js
models/Thread.js
models/User.js
models/index.js
package-lock.json
package.json
public/js/login.js
public/js/logout.js
seeds/index.js
seeds/post-seeds.js
seeds/thread-seeds.js
seeds/user-seeds.js
server.js
utils/auth.js
utils/helpers.js

Ali admin tasks

---

README.md

Upload video demo

---

README.md

upload youtube video
